/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResumesRouteImport } from './routes/_app.resumes'
import { Route as AppMatchingRouteImport } from './routes/_app.matching'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppHackathonRouteImport } from './routes/_app.hackathon'
import { Route as AppExportsRouteImport } from './routes/_app.exports'
import { Route as AppDatasetsRouteImport } from './routes/_app.datasets'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppCandidatesIndexRouteImport } from './routes/_app.candidates.index'
import { Route as ApiPublicRankRouteImport } from './routes/api/public/rank'
import { Route as AppCandidatesIdRouteImport } from './routes/_app.candidates.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesRoute = AppResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchingRoute = AppMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppHackathonRoute = AppHackathonRouteImport.update({
  id: '/hackathon',
  path: '/hackathon',
  getParentRoute: () => AppRoute,
} as any)
const AppExportsRoute = AppExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetsRoute = AppDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIndexRoute = AppCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicRankRoute = ApiPublicRankRouteImport.update({
  id: '/api/public/rank',
  path: '/api/public/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCandidatesIdRoute = AppCandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/datasets': typeof AppDatasetsRoute
  '/exports': typeof AppExportsRoute
  '/hackathon': typeof AppHackathonRoute
  '/insights': typeof AppInsightsRoute
  '/jobs': typeof AppJobsRoute
  '/matching': typeof AppMatchingRoute
  '/resumes': typeof AppResumesRoute
  '/settings': typeof AppSettingsRoute
  '/candidates/$id': typeof AppCandidatesIdRoute
  '/api/public/rank': typeof ApiPublicRankRoute
  '/candidates/': typeof AppCandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/datasets': typeof AppDatasetsRoute
  '/exports': typeof AppExportsRoute
  '/hackathon': typeof AppHackathonRoute
  '/insights': typeof AppInsightsRoute
  '/jobs': typeof AppJobsRoute
  '/matching': typeof AppMatchingRoute
  '/resumes': typeof AppResumesRoute
  '/settings': typeof AppSettingsRoute
  '/candidates/$id': typeof AppCandidatesIdRoute
  '/api/public/rank': typeof ApiPublicRankRoute
  '/candidates': typeof AppCandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/datasets': typeof AppDatasetsRoute
  '/_app/exports': typeof AppExportsRoute
  '/_app/hackathon': typeof AppHackathonRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/matching': typeof AppMatchingRoute
  '/_app/resumes': typeof AppResumesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/candidates/$id': typeof AppCandidatesIdRoute
  '/api/public/rank': typeof ApiPublicRankRoute
  '/_app/candidates/': typeof AppCandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/datasets'
    | '/exports'
    | '/hackathon'
    | '/insights'
    | '/jobs'
    | '/matching'
    | '/resumes'
    | '/settings'
    | '/candidates/$id'
    | '/api/public/rank'
    | '/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/datasets'
    | '/exports'
    | '/hackathon'
    | '/insights'
    | '/jobs'
    | '/matching'
    | '/resumes'
    | '/settings'
    | '/candidates/$id'
    | '/api/public/rank'
    | '/candidates'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/datasets'
    | '/_app/exports'
    | '/_app/hackathon'
    | '/_app/insights'
    | '/_app/jobs'
    | '/_app/matching'
    | '/_app/resumes'
    | '/_app/settings'
    | '/_app/candidates/$id'
    | '/api/public/rank'
    | '/_app/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicRankRoute: typeof ApiPublicRankRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes': {
      id: '/_app/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AppResumesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matching': {
      id: '/_app/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof AppMatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hackathon': {
      id: '/_app/hackathon'
      path: '/hackathon'
      fullPath: '/hackathon'
      preLoaderRoute: typeof AppHackathonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exports': {
      id: '/_app/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AppExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/datasets': {
      id: '/_app/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AppDatasetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates/': {
      id: '/_app/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AppCandidatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/rank': {
      id: '/api/public/rank'
      path: '/api/public/rank'
      fullPath: '/api/public/rank'
      preLoaderRoute: typeof ApiPublicRankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/candidates/$id': {
      id: '/_app/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AppCandidatesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatasetsRoute: typeof AppDatasetsRoute
  AppExportsRoute: typeof AppExportsRoute
  AppHackathonRoute: typeof AppHackathonRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppMatchingRoute: typeof AppMatchingRoute
  AppResumesRoute: typeof AppResumesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCandidatesIdRoute: typeof AppCandidatesIdRoute
  AppCandidatesIndexRoute: typeof AppCandidatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatasetsRoute: AppDatasetsRoute,
  AppExportsRoute: AppExportsRoute,
  AppHackathonRoute: AppHackathonRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppJobsRoute: AppJobsRoute,
  AppMatchingRoute: AppMatchingRoute,
  AppResumesRoute: AppResumesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCandidatesIdRoute: AppCandidatesIdRoute,
  AppCandidatesIndexRoute: AppCandidatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicRankRoute: ApiPublicRankRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
