// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Ensure your env file is configured.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();
    const defaultUserId = "00000000-0000-0000-0000-000000000000";
    const defaultClient = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    if (!request?.headers) {
      return next({
        context: {
          supabase: defaultClient,
          userId: defaultUserId,
          claims: { sub: defaultUserId } as any,
        },
      });
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return next({
        context: {
          supabase: defaultClient,
          userId: defaultUserId,
          claims: { sub: defaultUserId } as any,
        },
      });
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      return next({
        context: {
          supabase: defaultClient,
          userId: defaultUserId,
          claims: { sub: defaultUserId } as any,
        },
      });
    }

    try {
      const supabase = createClient<Database>(
        SUPABASE_URL,
        SUPABASE_PUBLISHABLE_KEY,
        {
          global: {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );

      const { data, error } = await supabase.auth.getClaims(token);
      if (error || !data?.claims?.sub) {
        return next({
          context: {
            supabase: defaultClient,
            userId: defaultUserId,
            claims: { sub: defaultUserId } as any,
          },
        });
      }

      return next({
        context: {
          supabase,
          userId: data.claims.sub,
          claims: data.claims as any,
        },
      });
    } catch {
      return next({
        context: {
          supabase: defaultClient,
          userId: defaultUserId,
          claims: { sub: defaultUserId } as any,
        },
      });
    }
  },
);
